первая и вторая задачи первого урока
js-tasks-ru/jsbasic-20221028_evgenii80 pull request #2
Opened 2022-11-07 20:36 UTC by Enik85

2022-11-07 20:37 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-08 06:14 UTC, koalex requested changes
Исправить замечание в **1-1**

2022-11-08 06:14 UTC, koalex commented on 1-module/1-task/index.js
> +alert(`результат ${factorial(+meaning)}`);
Удалить `alert`

2022-11-08 14:00 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-09 09:45 UTC, Enik85 commented on 1-module/1-task/index.js
> +alert(`результат ${factorial(+meaning)}`);
Внес изменения в 1-1 (удалил alert)

2022-11-10 04:22 UTC, koalex approved these changes

2022-11-10 04:23 UTC, merged